SELECT * FROM DEPT WHERE DEPTNO = 30;

INSERT INTO DEPT VALUES (70, 'MARKETING', 'SEOUL');

UPDATE DEPT SET DNAME = 'CLEANNING', LOC='SUWON' WHERE DEPTNO = 70;

SELECT * FROM DEPT;

SELECT * FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES');

SELECT COUNT(*) CNT FROM DEPT WHERE DEPTNO = 30;